import type { Metadata } from "next";

import { LegalDocument } from "@/components/legal/legal-document";

export const metadata: Metadata = {
  title: "Cookie Policy",
  description:
    "What cookies and tracking technologies CrackVILT uses, why, and how to control or revoke your consent at any time.",
  robots: { index: true, follow: true },
  alternates: { canonical: "/cookies" },
};

/**
 * Cookie Policy of crackvilt.com.
 *
 * As with the Privacy Policy, the original text was generated by
 * Iubenda based on the site's tracker inventory and the publisher
 * (CrackVILT) information. We host it ourselves so we can drop the
 * Iubenda subscription. Wording is unchanged from the Iubenda render
 * to keep the legal vetting intact.
 */
export default function CookiePolicyPage() {
  return (
    <LegalDocument
      title="Cookie Policy of crackvilt.com"
      intro="Welcome to the cookie policy of crackvilt.com. This policy will help you understand what cookies and tracking technologies we use, how we use them and what your rights are in relation to it."
      lastUpdate="22 May 2026"
    >
      <h2>Introduction</h2>
      <p>
        This document informs Users about the technologies that help this Website to achieve the
        purposes described below. Such technologies allow the Owner to access and store information
        (for example by using a Cookie) or use resources (for example by running a script) on a
        User&apos;s device as they interact with this Website.
      </p>
      <p>
        For simplicity, all such technologies are defined as &ldquo;Trackers&rdquo; within this
        document — unless there is a reason to differentiate. For example, while Cookies can be used
        on both web and mobile browsers, it would be inaccurate to talk about Cookies in the context
        of mobile apps as they are a browser-based Tracker. For this reason, within this document,
        the term Cookies is only used where it is specifically meant to indicate that particular
        type of Tracker.
      </p>
      <p>
        Some of the purposes for which Trackers are used may also require the User&apos;s consent.
        Whenever consent is given, it can be freely withdrawn at any time following the instructions
        provided in this document.
      </p>
      <p>
        This Website uses Trackers managed directly by the Owner (so-called
        &ldquo;first-party&rdquo; Trackers) and Trackers that enable services provided by a
        third-party (so-called &ldquo;third-party&rdquo; Trackers). Unless otherwise specified
        within this document, third-party providers may access the Trackers managed by them.
      </p>
      <p>
        The validity and expiration periods of Cookies and other similar Trackers may vary depending
        on the lifetime set by the Owner or the relevant provider. Some of them expire upon
        termination of the User&apos;s browsing session.
      </p>
      <p>
        In addition to what&apos;s specified in the descriptions within each of the categories
        below, Users may find more precise and updated information regarding lifetime specification
        as well as any other relevant information — such as the presence of other Trackers — in the
        linked privacy policies of the respective third-party providers or by contacting the Owner.
      </p>

      <h2>Owner and Data Controller</h2>
      <p>
        <strong>CrackVILT</strong> &mdash; operated by Giuliano Giannini, an individual data
        controller based in the United Kingdom.
      </p>
      <p>For any data protection request, complaint, or other GDPR matter, please contact:</p>
      <p>
        <strong>Owner contact email:</strong>{" "}
        <a href="mailto:info@crackvilt.com">info@crackvilt.com</a>
      </p>

      <h2>How this Website uses Trackers</h2>

      <h3>Necessary</h3>
      <p>
        This Website uses so-called &ldquo;technical&rdquo; Cookies and other similar Trackers to
        carry out activities that are strictly necessary for the operation or delivery of the
        Service.
      </p>
      <h4>Trackers managed by third parties — Supabase, Inc.</h4>
      <p>
        <strong>Supabase</strong>
      </p>
      <p>
        <strong>Company:</strong> Supabase, Inc.
      </p>
      <p>
        <strong>Place of processing:</strong> Singapore
      </p>
      <p>
        <strong>Personal Data processed:</strong> Trackers; Usage Data; various types of Data as
        specified in the privacy policy of the service.
      </p>

      <h3>Measurement</h3>
      <p>
        This Website uses Trackers to measure traffic and analyse User behavior to improve the
        Service.
      </p>
      <h4>Trackers managed by third parties — Amplitude Inc.</h4>
      <p>
        <strong>Amplitude Analytics</strong>
      </p>
      <p>
        <strong>Company:</strong> Amplitude Inc.
      </p>
      <p>
        <strong>Place of processing:</strong> United States
      </p>
      <p>
        <strong>Personal Data processed:</strong> browsing history; device information; Trackers;
        Usage Data.
      </p>

      <h2>How to manage preferences and provide or withdraw consent on this Website</h2>
      <p>
        Whenever the use of Trackers is based on consent, users can provide or withdraw such consent
        by setting or updating their preferences via the relevant privacy choices panel available on
        this Website. The cookie banner can be reopened at any time using the &ldquo;Cookie
        preferences&rdquo; link in the footer.
      </p>
      <p>
        With regard to any third-party Trackers, Users can manage their preferences via the related
        opt-out link (where provided), by using the means indicated in the third party&apos;s
        privacy policy, or by contacting the third party.
      </p>

      <h2>How to control or delete Cookies and similar technologies via your device settings</h2>
      <p>Users may use their own browser settings to:</p>
      <ul>
        <li>See what Cookies or other similar technologies have been set on the device;</li>
        <li>Block Cookies or similar technologies;</li>
        <li>Clear Cookies or similar technologies from the browser.</li>
      </ul>
      <p>The browser settings, however, do not allow granular control of consent by category.</p>
      <p>
        Users can find information about how to manage Cookies in the most commonly used browsers at
        the following addresses:
      </p>
      <ul>
        <li>
          <a
            href="https://support.google.com/chrome/answer/95647"
            target="_blank"
            rel="noopener noreferrer"
          >
            Google Chrome
          </a>
        </li>
        <li>
          <a
            href="https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop"
            target="_blank"
            rel="noopener noreferrer"
          >
            Mozilla Firefox
          </a>
        </li>
        <li>
          <a
            href="https://support.apple.com/en-gb/guide/safari/sfri11471/mac"
            target="_blank"
            rel="noopener noreferrer"
          >
            Apple Safari
          </a>
        </li>
        <li>
          <a
            href="https://support.microsoft.com/en-us/microsoft-edge/delete-cookies-in-microsoft-edge-63947406-40ac-c3b8-57b9-2a946a29ae09"
            target="_blank"
            rel="noopener noreferrer"
          >
            Microsoft Edge
          </a>
        </li>
        <li>
          <a
            href="https://support.brave.com/hc/en-us/articles/360050634711"
            target="_blank"
            rel="noopener noreferrer"
          >
            Brave
          </a>
        </li>
        <li>
          <a
            href="https://help.opera.com/en/latest/web-preferences/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Opera
          </a>
        </li>
      </ul>
      <p>
        Users may also manage certain categories of Trackers used on mobile apps by opting out
        through relevant device settings such as the device advertising settings for mobile devices,
        or tracking settings in general (Users may open the device settings and look for the
        relevant setting).
      </p>

      <h2>Consequences of denying consent</h2>
      <p>
        Users are free to decide whether or not to grant consent. However, please note that Trackers
        help this Website to provide a better experience and advanced functionalities to Users (in
        line with the purposes outlined in this document). Therefore, in the absence of the
        User&apos;s consent, the Owner may be unable to provide related features.
      </p>

      <h2>Definitions and legal references</h2>
      <dl>
        <dt>Personal Data (or Data)</dt>
        <dd>
          Any information that directly, indirectly, or in connection with other information —
          including a personal identification number — allows for the identification or
          identifiability of a natural person.
        </dd>
        <dt>Usage Data</dt>
        <dd>
          Information collected automatically through this Website (or third-party services employed
          in this Website), which can include: the IP addresses or domain names of the computers
          utilised by the Users who use this Website, the URI addresses (Uniform Resource
          Identifier), the time of the request, the method utilised to submit the request to the
          server, the size of the file received in response, the numerical code indicating the
          status of the server&apos;s answer (successful outcome, error, etc.), the country of
          origin, the features of the browser and the operating system utilised by the User, the
          various time details per visit (e.g., the time spent on each page within the Application)
          and the details about the path followed within the Application with special reference to
          the sequence of pages visited, and other parameters about the device operating system
          and/or the User&apos;s IT environment.
        </dd>
        <dt>User</dt>
        <dd>
          The individual using this Website who, unless otherwise specified, coincides with the Data
          Subject.
        </dd>
        <dt>Data Subject</dt>
        <dd>The natural person to whom the Personal Data refers.</dd>
        <dt>Data Controller (or Owner)</dt>
        <dd>
          The natural or legal person, public authority, agency or other body which, alone or
          jointly with others, determines the purposes and means of the processing of Personal Data,
          including the security measures concerning the operation and use of this Website. The Data
          Controller, unless otherwise specified, is the Owner of this Website.
        </dd>
        <dt>This Website (or this Application)</dt>
        <dd>The means by which the Personal Data of the User is collected and processed.</dd>
        <dt>Cookie</dt>
        <dd>
          Cookies are Trackers consisting of small sets of data stored in the User&apos;s browser.
        </dd>
        <dt>Tracker</dt>
        <dd>
          Tracker indicates any technology — e.g. Cookies, unique identifiers, web beacons, embedded
          scripts, e-tags and fingerprinting — that enables the tracking of Users, for example by
          accessing or storing information on the User&apos;s device.
        </dd>
      </dl>

      <h3>Legal information</h3>
      <p>
        This policy relates solely to this Website, if not stated otherwise within this document.
        The Privacy Policy of this Website can be found at <a href="/privacy">/privacy</a>.
      </p>
    </LegalDocument>
  );
}
