import type { Metadata } from "next";

import { LegalDocument } from "@/components/legal/legal-document";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How CrackVILT collects and processes personal data, what your rights are, and the third parties involved in delivering this website.",
  robots: { index: true, follow: true },
};

/**
 * Privacy Policy of crackvilt.com.
 *
 * Original text was generated by Iubenda based on the data processing
 * activities of the site (services list, owner info, jurisdiction).
 * Following Iubenda's Terms of Service the generated content belongs
 * to the publisher; we host it ourselves so we can drop the Iubenda
 * subscription. The structure mirrors Iubenda's reference template
 * because that template is well-known to UK ICO / EDPB and matches
 * the Cookie Policy on the same site.
 */
export default function PrivacyPolicyPage() {
  return (
    <LegalDocument
      title="Privacy Policy of crackvilt.com"
      intro="Welcome to the privacy policy of crackvilt.com. This policy will help you understand what data we collect, why we collect it, and what your rights are in relation to it."
      lastUpdate="22 May 2026"
    >
      <h2>Owner and Data Controller</h2>
      <address>
        <strong>CrackVILT</strong>
        <br />
        67 Sigrist Square,
        <br />
        Kingston upon Thames
        <br />
        KT2 6JY
      </address>
      <p>
        <strong>Owner contact email:</strong>{" "}
        <a href="mailto:[email protected]">[email protected]</a>
      </p>

      <h2>Types of Data we collect</h2>
      <p>
        Among the types of Personal Data that this Website collects, by itself or through third
        parties, there are:
      </p>
      <ul>
        <li>Trackers</li>
        <li>Usage Data</li>
        <li>browsing history</li>
        <li>device information</li>
      </ul>
      <p>
        Complete details on each type of Personal Data collected are provided in the dedicated
        sections of this privacy policy or by specific explanation texts displayed prior to the Data
        collection.
      </p>
      <p>
        Personal Data may be freely provided by the User, or, in case of Usage Data, collected
        automatically when using this Website.
      </p>
      <p>
        Unless specified otherwise, all Data requested by this Website is mandatory and failure to
        provide this Data may make it impossible for this Website to provide its services. In cases
        where this Website specifically states that some Data is not mandatory, Users are free not
        to communicate this Data without consequences to the availability or the functioning of the
        Service.
      </p>
      <p>
        Users who are uncertain about which Personal Data is mandatory are welcome to contact the
        Owner.
      </p>
      <p>
        Any use of Cookies — or of other tracking tools — by this Website or by the owners of
        third-party services used by this Website serves the purpose of providing the Service
        required by the User, in addition to any other purposes described in the present document
        and in the Cookie Policy.
      </p>
      <p>
        Users are responsible for any third-party Personal Data obtained, published or shared
        through this Website.
      </p>

      <h2>Mode and place of processing the Data</h2>
      <h3>Methods of processing</h3>
      <p>
        The Owner takes appropriate security measures to prevent unauthorised access, disclosure,
        modification, or unauthorised destruction of the Data.
      </p>
      <p>
        The Data processing is carried out using computers and/or IT enabled tools, following
        organisational procedures and modes strictly related to the purposes indicated. In addition
        to the Owner, in some cases, the Data may be accessible to certain types of persons in
        charge, involved with the operation of this Website (administration, sales, marketing,
        legal, system administration) or external parties (such as third-party technical service
        providers, mail carriers, hosting providers, IT companies, communications agencies)
        appointed, if necessary, as Data Processors by the Owner. The updated list of these parties
        may be requested from the Owner at any time.
      </p>

      <h3>Place</h3>
      <p>
        The Data is processed at the Owner&apos;s operating offices and in any other places where
        the parties involved in the processing are located.
      </p>
      <p>
        Depending on the User&apos;s location, data transfers may involve transferring the
        User&apos;s Data to a country other than their own. To find out more about the place of
        processing of such transferred Data, Users can check the section containing details about
        the processing of Personal Data.
      </p>

      <h3>Retention time</h3>
      <p>
        Personal Data shall be processed and stored for as long as required by the purpose they have
        been collected for.
      </p>

      <h2>The purposes of processing</h2>
      <p>
        The Data concerning the User is collected to allow the Owner to provide its Service, comply
        with its legal obligations, respond to enforcement requests, protect its rights and
        interests (or those of its Users or third parties), detect any malicious or fraudulent
        activity, as well as the following:
      </p>
      <ul>
        <li>Analytics</li>
        <li>Hosting and backend infrastructure</li>
        <li>Traffic optimisation and distribution</li>
      </ul>

      <h2>Detailed information on the processing of Personal Data</h2>

      <h3>Analytics</h3>
      <p>
        The services contained in this section enable the Owner to monitor and analyse web traffic
        and can be used to keep track of User behaviour.
      </p>
      <h4>Amplitude Analytics</h4>
      <p>Amplitude Analytics is an analytics service provided by Amplitude Inc.</p>
      <p>
        <strong>Personal Data processed:</strong> browsing history; device information; Trackers;
        Usage Data.
      </p>
      <p>
        <strong>Service provided by:</strong> Amplitude Inc. (United States) —{" "}
        <a href="https://amplitude.com/privacy" target="_blank" rel="noopener noreferrer">
          Privacy Policy
        </a>
        .
      </p>

      <h3>Hosting and backend infrastructure</h3>
      <p>
        This type of service has the purpose of hosting Data and files that enable this Website to
        run and be distributed or to provide a ready-made infrastructure to run specific features or
        parts of this Website.
      </p>
      <p>
        Some services among those listed below, if any, may work through geographically distributed
        servers, making it difficult to determine the actual location where the Personal Data are
        stored.
      </p>
      <h4>Supabase</h4>
      <p>Supabase is a hosting and backend service provided by Supabase, Inc.</p>
      <p>
        <strong>Personal Data processed:</strong> Trackers; Usage Data; various types of Data as
        specified in the privacy policy of the service.
      </p>
      <p>
        <strong>Service provided by:</strong> Supabase, Inc. (Singapore) —{" "}
        <a href="https://supabase.com/privacy" target="_blank" rel="noopener noreferrer">
          Privacy Policy
        </a>
        .
      </p>
      <h4>Vercel</h4>
      <p>Vercel is a hosting and backend service provided by Vercel Inc.</p>
      <p>
        <strong>Personal Data processed:</strong> Usage Data; various types of Data as specified in
        the privacy policy of the service.
      </p>
      <p>
        <strong>Service provided by:</strong> Vercel Inc. (United States) —{" "}
        <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">
          Privacy Policy
        </a>
        .
      </p>

      <h3>Traffic optimisation and distribution</h3>
      <p>
        This type of service allows this Website to distribute their content using servers located
        across different countries and to optimise their performance. Which Personal Data are
        processed depends on the characteristics and the way these services are implemented. Their
        function is to filter communications between this Website and the User&apos;s browser.
        Considering the widespread distribution of this system, it is difficult to determine the
        locations to which the contents that may contain Personal Information of the User are
        transferred.
      </p>
      <h4>Cloudflare DNS</h4>
      <p>
        Cloudflare DNS is a managed domain name system (DNS) service provided by Cloudflare, Inc.
        Cloudflare DNS manages DNS infrastructure to deliver traffic quickly and securely.
      </p>
      <p>
        <strong>Personal Data processed:</strong> Usage Data.
      </p>
      <p>
        <strong>Service provided by:</strong> Cloudflare, Inc. (United States) —{" "}
        <a
          href="https://www.cloudflare.com/privacypolicy/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Privacy Policy
        </a>
        .
      </p>

      <h2>Cookie Policy</h2>
      <p>
        This Website uses Trackers. To learn more, Users may consult the{" "}
        <a href="/cookies">Cookie Policy</a>.
      </p>

      <h2>Further Information for Users in the European Union</h2>

      <h3>Legal basis of processing</h3>
      <p>The Owner may process Personal Data relating to Users if one of the following applies:</p>
      <ul>
        <li>Users have given their consent for one or more specific purposes.</li>
        <li>
          provision of Data is necessary for the performance of an agreement with the User and/or
          for any pre-contractual obligations thereof;
        </li>
        <li>
          processing is necessary for compliance with a legal obligation to which the Owner is
          subject;
        </li>
        <li>
          processing is related to a task that is carried out in the public interest or in the
          exercise of official authority vested in the Owner;
        </li>
        <li>
          processing is necessary for the purposes of the legitimate interests pursued by the Owner
          or by a third party.
        </li>
      </ul>
      <p>
        In any case, the Owner will gladly help to clarify the specific legal basis that applies to
        the processing, and in particular whether the provision of Personal Data is a statutory or
        contractual requirement, or a requirement necessary to enter into a contract.
      </p>

      <h3>Further information about retention time</h3>
      <p>
        Personal Data shall be processed and stored for as long as required by the purpose they have
        been collected for.
      </p>
      <p>Therefore:</p>
      <ul>
        <li>
          Personal Data collected for purposes related to the performance of a contract between the
          Owner and the User shall be retained until such contract has been fully performed.
        </li>
        <li>
          Personal Data collected for the purposes of the Owner&apos;s legitimate interests shall be
          retained as long as needed to fulfill such purposes. Users may find specific information
          regarding the legitimate interests pursued by the Owner within the relevant sections of
          this document or by contacting the Owner.
        </li>
      </ul>
      <p>
        The Owner may be allowed to retain Personal Data for a longer period whenever the User has
        given consent to such processing, as long as such consent is not withdrawn. Furthermore, the
        Owner may be obliged to retain Personal Data for a longer period whenever required to fulfil
        a legal obligation or upon order of an authority.
      </p>
      <p>
        Once the retention period expires, Personal Data shall be deleted. Therefore, the right of
        access, the right to erasure, the right to rectification and the right to data portability
        cannot be enforced after expiration of the retention period.
      </p>

      <h3>The rights of Users based on the General Data Protection Regulation (GDPR)</h3>
      <p>Users may exercise certain rights regarding their Data processed by the Owner.</p>
      <p>
        In particular, Users have the right to do the following, to the extent permitted by law:
      </p>
      <ul>
        <li>
          <strong>Withdraw their consent at any time.</strong> Users have the right to withdraw
          consent where they have previously given their consent to the processing of their Personal
          Data.
        </li>
        <li>
          <strong>Object to processing of their Data.</strong> Users have the right to object to the
          processing of their Data if the processing is carried out on a legal basis other than
          consent.
        </li>
        <li>
          <strong>Access their Data.</strong> Users have the right to learn if Data is being
          processed by the Owner, obtain disclosure regarding certain aspects of the processing and
          obtain a copy of the Data undergoing processing.
        </li>
        <li>
          <strong>Verify and seek rectification.</strong> Users have the right to verify the
          accuracy of their Data and ask for it to be updated or corrected.
        </li>
        <li>
          <strong>Restrict the processing of their Data.</strong> Users have the right to restrict
          the processing of their Data. In this case, the Owner will not process their Data for any
          purpose other than storing it.
        </li>
        <li>
          <strong>Have their Personal Data deleted or otherwise removed.</strong> Users have the
          right to obtain the erasure of their Data from the Owner.
        </li>
        <li>
          <strong>Receive their Data and have it transferred to another controller.</strong> Users
          have the right to receive their Data in a structured, commonly used and machine readable
          format and, if technically feasible, to have it transmitted to another controller without
          any hindrance.
        </li>
        <li>
          <strong>Lodge a complaint.</strong> Users have the right to bring a claim before their
          competent data protection authority.
        </li>
      </ul>
      <p>
        Users are also entitled to learn about the legal basis of Data transfers to a country
        outside the European Union or to any international organisation governed by public
        international law or set up by two or more countries, such as the UN, and about the security
        measures taken by the Owner to safeguard their Data.
      </p>
      <p>
        If any such transfer takes place, Users can find out more by checking the relevant sections
        of this document or enquire with the Owner using the information provided in the contact
        section.
      </p>

      <h3>Details about the right to object to processing</h3>
      <p>
        Where Personal Data is processed for a public interest, in the exercise of an official
        authority vested in the Owner or for the purposes of the legitimate interests pursued by the
        Owner, Users may object to such processing by providing a ground related to their particular
        situation to justify the objection.
      </p>
      <p>
        Users must know that, however, should their Personal Data be processed for direct marketing
        purposes, they can object to that processing at any time, free of charge and without
        providing any justification. Where the User objects to processing for direct marketing
        purposes, the Personal Data will no longer be processed for such purposes. To learn whether
        the Owner is processing Personal Data for direct marketing purposes, Users may refer to the
        relevant sections of this document.
      </p>

      <h3>How to exercise these rights</h3>
      <p>
        Any requests to exercise User rights can be directed to the Owner through the contact
        details provided in this document. Such requests are free of charge and will be answered by
        the Owner as early as possible and always within one month, providing Users with the
        information required by law. Any rectification or erasure of Personal Data or restriction of
        processing will be communicated by the Owner to each recipient, if any, to whom the Personal
        Data has been disclosed unless this proves impossible or involves disproportionate effort.
        At the Users&apos; request, the Owner will inform them about those recipients.
      </p>

      <h2>Additional information about Data collection and processing</h2>

      <h3>Legal action</h3>
      <p>
        The User&apos;s Personal Data may be used for legal purposes by the Owner in Court or in the
        stages leading to possible legal action arising from improper use of this Website or the
        related Services. The User declares to be aware that the Owner may be required to reveal
        personal data upon request of public authorities.
      </p>

      <h3>Additional information about User&apos;s Personal Data</h3>
      <p>
        In addition to the information contained in this privacy policy, this Website may provide
        the User with additional and contextual information concerning particular Services or the
        collection and processing of Personal Data upon request.
      </p>

      <h3>System logs and maintenance</h3>
      <p>
        For operation and maintenance purposes, this Website and any third-party services may
        collect files that record interaction with this Website (System logs) or use other Personal
        Data (such as the IP Address) for this purpose.
      </p>

      <h3>Information not contained in this policy</h3>
      <p>
        More details concerning the collection or processing of Personal Data may be requested from
        the Owner at any time. Please see the contact information at the beginning of this document.
      </p>

      <h3>Changes to this privacy policy</h3>
      <p>
        The Owner reserves the right to make changes to this privacy policy at any time by notifying
        its Users on this page and possibly within this Website and/or — as far as technically and
        legally feasible — sending a notice to Users via any contact information available to the
        Owner. It is strongly recommended to check this page often, referring to the date of the
        last modification listed at the bottom.
      </p>
      <p>
        Should the changes affect processing activities performed on the basis of the User&apos;s
        consent, the Owner shall collect new consent from the User, where required.
      </p>

      <h2>Definitions and legal references</h2>
      <dl>
        <dt>Personal Data (or Data)</dt>
        <dd>
          Any information that directly, indirectly, or in connection with other information —
          including a personal identification number — allows for the identification or
          identifiability of a natural person.
        </dd>
        <dt>Usage Data</dt>
        <dd>
          Information collected automatically through this Website (or third-party services employed
          in this Website), which can include: the IP addresses or domain names of the computers
          utilised by the Users who use this Website, the URI addresses (Uniform Resource
          Identifier), the time of the request, the method utilised to submit the request to the
          server, the size of the file received in response, the numerical code indicating the
          status of the server&apos;s answer (successful outcome, error, etc.), the country of
          origin, the features of the browser and the operating system utilised by the User, the
          various time details per visit (e.g., the time spent on each page within the Application)
          and the details about the path followed within the Application with special reference to
          the sequence of pages visited, and other parameters about the device operating system
          and/or the User&apos;s IT environment.
        </dd>
        <dt>User</dt>
        <dd>
          The individual using this Website who, unless otherwise specified, coincides with the Data
          Subject.
        </dd>
        <dt>Data Subject</dt>
        <dd>The natural person to whom the Personal Data refers.</dd>
        <dt>Data Processor (or Processor)</dt>
        <dd>
          The natural or legal person, public authority, agency or other body which processes
          Personal Data on behalf of the Controller, as described in this privacy policy.
        </dd>
        <dt>Data Controller (or Owner)</dt>
        <dd>
          The natural or legal person, public authority, agency or other body which, alone or
          jointly with others, determines the purposes and means of the processing of Personal Data,
          including the security measures concerning the operation and use of this Website. The Data
          Controller, unless otherwise specified, is the Owner of this Website.
        </dd>
        <dt>This Website (or this Application)</dt>
        <dd>The means by which the Personal Data of the User is collected and processed.</dd>
        <dt>Service</dt>
        <dd>
          The service provided by this Website as described in the relative terms (if available) and
          on this site/application.
        </dd>
        <dt>European Union (or EU)</dt>
        <dd>
          Unless otherwise specified, all references made within this document to the European Union
          include all current member states to the European Union and the European Economic Area.
        </dd>
        <dt>Cookie</dt>
        <dd>
          Cookies are Trackers consisting of small sets of data stored in the User&apos;s browser.
        </dd>
        <dt>Tracker</dt>
        <dd>
          Tracker indicates any technology — e.g. Cookies, unique identifiers, web beacons, embedded
          scripts, e-tags and fingerprinting — that enables the tracking of Users, for example by
          accessing or storing information on the User&apos;s device.
        </dd>
      </dl>

      <h3>Legal information</h3>
      <p>
        This policy relates solely to this Website, if not stated otherwise within this document.
      </p>
    </LegalDocument>
  );
}
